# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否验证过'),
        ),
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(auto_now=True, verbose_name='发送时间'),
        ),
    ]
