# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-10 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180410_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='添加时间'),
        ),
    ]
