# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-11 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180410_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.CharField(choices=[('ty', '体育'), ('yl', '娱乐'), ('jr', '金融'), ('qc', '汽车')], default='qc', max_length=10, verbose_name='类别'),
        ),
    ]
