# Generated by Django 2.0.2 on 2018-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20180321_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindex',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
