# Generated by Django 2.0.2 on 2018-03-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20180320_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='templates',
            field=models.ManyToManyField(blank=True, to='monitor.Template'),
        ),
        migrations.AlterField(
            model_name='service',
            name='has_sub_service',
            field=models.BooleanField(default=False, help_text='如果一个服务还有独立的子服务 ,选择这个,比如 网卡服务有多个独立的子网卡', verbose_name='是否有子服务'),
        ),
    ]
