# Generated by Django 2.0.2 on 2018-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20180320_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='templates',
            field=models.ManyToManyField(blank=True, to='monitor.Template'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='名称'),
        ),
    ]
