# Generated by Django 2.0.2 on 2018-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_action_actionoperation_classroom_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ManyToManyField(to='monitor.Classroom'),
        ),
    ]
