# Generated by Django 2.0.2 on 2018-03-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_auto_20180320_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
