# Generated by Django 2.0.2 on 2018-03-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_auto_20180320_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionoperation',
            name='action_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('script', 'RunScript')], default='email', max_length=64, verbose_name='动作类型'),
        ),
        migrations.AddField(
            model_name='actionoperation',
            name='msg_format',
            field=models.TextField(default='Host({hostname}, {ip}) service({service_name}) has issue, msg:{msg}', verbose_name='消息格式'),
        ),
        migrations.AddField(
            model_name='actionoperation',
            name='step',
            field=models.SmallIntegerField(default=1, help_text='当trigger触发次数小于这个值时就执行这条记录里报警方式', verbose_name='第n次告警'),
        ),
    ]
