# Generated by Django 2.0.2 on 2018-03-20 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0010_auto_20180320_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='action',
            name='host_groups',
            field=models.ManyToManyField(blank=True, to='monitor.HostGroup'),
        ),
        migrations.AddField(
            model_name='action',
            name='hosts',
            field=models.ManyToManyField(blank=True, to='monitor.Host'),
        ),
        migrations.AddField(
            model_name='action',
            name='interval',
            field=models.IntegerField(default=300, verbose_name='告警间隔'),
        ),
        migrations.AddField(
            model_name='action',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True, verbose_name='名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='operations',
            field=models.ManyToManyField(to='monitor.ActionOperation'),
        ),
        migrations.AddField(
            model_name='action',
            name='recover_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='recover_notice',
            field=models.BooleanField(default=True, verbose_name='故障恢复后发送通知消息'),
        ),
        migrations.AddField(
            model_name='action',
            name='recover_subject',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='actionoperation',
            name='name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
    ]
