# Generated by Django 2.0.2 on 2018-03-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_triggerexpression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceindex',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
